# -*- coding: utf-8 -*-
from pathlib import Path

root = Path(__file__).resolve().parent

replacements = [
    ("学校选课系统", "Course Selection System"),
    ("选课管理系统", "Course Selection System"),
    ("选课管理", "Course Selection"),
    ("管理系统", " System"),
    ("管理员", "Admin"),
    ("新增", "Add "),
    ("地址", "Location"),
    ("人数", "Enrollment"),
    ("退选", "Drop"),
    ("选择", "Select"),
    ("权限名", "Permission Name"),
    ("权限详情", "Permission Detail"),
    ("确定要Delete吗？", "Delete this item?"),
    ("是否Delete？", "Delete this item?"),
    ("是否Course Selection？", "Select this course?"),
    ("是否退选？", "Drop this course?"),
    ("已存在", " already exists"),
    ("pages面", ""),
    ("Open Courses成功", "Opened successfully"),
    ("System员", "System Administrator"),
    ("登录系统", "Sign in"),
    ("登录失败咯， 请", "Sign-in failed. Please "),
    ("重新登录", "sign in again"),
    ("登录失败", "Sign-in Failed"),
    ("登录", "Sign In"),
    ("验证码", "Verification Code"),
    ("账号", "Account"),
    ("密码", "Password"),
    ("注销", "Sign Out"),
    ("在线", "Online"),
    ("菜单", "Menu"),
    ("系统管理", "System"),
    ("管理员管理", "Admin Management"),
    ("角色管理", "Role Management"),
    ("权限管理", "Permission Management"),
    ("信息管理", "Information"),
    ("教师信息管理", "Teacher Management"),
    ("学生信息管理", "Student Management"),
    ("课程信息管理", "Course Management"),
    ("开课管理", "Teaching Plan"),
    ("开设课程", "Opened Courses"),
    ("公共选课", "Available Courses"),
    ("我的课程", "My Courses"),
    ("管理员信息表单", "Admin Form"),
    ("管理员信息", "Admin Information"),
    ("管理员列表", "Admin List"),
    ("管理员角色", "Admin Roles"),
    ("新增管理员", "Add Admin"),
    ("修改管理员信息页面", "Edit Admin"),
    ("管理员信息页面", "Admins"),
    ("教师信息列表", "Teacher List"),
    ("教师信息表单", "Teacher Form"),
    ("教师信息", "Teacher Information"),
    ("新增教师页面", "Add Teacher"),
    ("修改教师信息页面", "Edit Teacher"),
    ("教师信息页面", "Teachers"),
    ("学生信息列表", "Student List"),
    ("学生信息表单", "Student Form"),
    ("学生信息", "Student Information"),
    ("新增学生页面", "Add Student"),
    ("修改学生信息页面", "Edit Student"),
    ("学生信息页面", "Students"),
    ("课程信息列表", "Course List"),
    ("课程信息表单", "Course Form"),
    ("课程信息", "Course Information"),
    ("新增课程页面", "Add Course"),
    ("修改课程信息页面", "Edit Course"),
    ("课程计划信息", "Teaching Plan Information"),
    ("课程计划列表", "Teaching Plan List"),
    ("课程计划", "Teaching Plan"),
    ("新增课程计划", "Add Teaching Plan"),
    ("修改课程计划信息页面", "Edit Teaching Plan"),
    ("可选课程计划", "Available Courses"),
    ("已选课程计划", "Selected Courses"),
    ("角色信息", "Role Information"),
    ("角色列表", "Role List"),
    ("新增角色", "Add Role"),
    ("角色名称", "Role Name"),
    ("角色描述", "Role Description"),
    ("角色权限", "Role Permissions"),
    ("权限信息", "Permission Information"),
    ("权限列表", "Permission List"),
    ("新增权限", "Add Permission"),
    ("权限名称", "Permission Name"),
    ("权限描述", "Permission URL"),
    ("课程名", "Course Name"),
    ("课程介绍", "Course Description"),
    ("课程描述", "Course Description"),
    ("列表", "List"),
    ("新建", "New"),
    ("搜索", "Search"),
    ("保存", "Save"),
    ("返回", "Back"),
    ("修改", "Edit"),
    ("删除", "Delete"),
    ("操作", "Actions"),
    ("查看详情", "Details"),
    ("分配角色", "Assign Roles"),
    ("分配权限", "Assign Permissions"),
    ("是否删除？", "Delete this item?"),
    ("添加失败,课程已存在", "Add failed: course already exists"),
    ("添加失败,用户已存在", "Add failed: account already exists"),
    ("添加失败", "Add failed"),
    ("添加成功", "Added successfully"),
    ("删除成功", "Deleted successfully"),
    ("修改成功", "Updated successfully"),
    ("退选成功", "Dropped successfully"),
    ("选课成功", "Selected successfully"),
    ("工号", "Employee ID"),
    ("学号", "Student ID"),
    ("姓名", "Name"),
    ("名字", "Name"),
    ("性别", "Gender"),
    ("男", "Male"),
    ("女", "Female"),
    ("电话", "Phone"),
    ("邮箱", "Email"),
    ("邮件", "Email"),
    ("职位", "Position"),
    ("生日", "Birthday"),
    ("班级名", "Class Name"),
    ("班级", "Class"),
    ("班主任", "Head Teacher"),
    ("学时", "Class Hours"),
    ("学分", "Credits"),
    ("地点", "Location"),
    ("选课人数", "Enrollment"),
    ("任课教师", "Teacher"),
    ("总共", "Total"),
    ("条数据", "records"),
    ("上一页", "Previous"),
    ("下一页", "Next"),
    ("末页", "Last"),
    ("首页", "Home"),
    ("欢迎━(*｀∀´*)ノ亻!", "Welcome!"),
    ("出错了，请检查你的操作是否有误。。。。", "Something went wrong. Please check your operation."),
    ("如有问题，请和我们联系", "For support, contact "),
    ("超级管理员", "Super Admin"),
    ("系统管理员", "System Administrator"),
    ("学校老师", "School Teacher"),
    ("学校学生", "School Student"),
    ("课程管理员", "Course Admin"),
    ("管理学校课程库信息", "Manage course catalog"),
    ("教师管理员", "Teacher Admin"),
    ("管理学校教师信息", "Manage teacher records"),
    ("学生管理员", "Student Admin"),
    ("管理学校学生信息", "Manage student records"),
    ("开课", "Open Courses"),
    ("选课", "Course Selection"),
    ("课程", "Course"),
    ("教师", "Teacher"),
    ("学生", "Student"),
    ("页", "pages"),
    ("共", "Total"),
]

targets = [root / "README.md", root / "css.sql"]
targets += list((root / "src/main/resources/templates").rglob("*.html"))
targets += list((root / "src/main/java").rglob("*.java"))

for path in targets:
    text = path.read_text(encoding="utf-8")
    for old, new in replacements:
        text = text.replace(old, new)
    if path.suffix == ".html" and '<meta charset=' not in text:
        text = text.replace("<head>", '<head>\n    <meta charset="UTF-8">', 1)
    path.write_text(text, encoding="utf-8", newline="")
